# Generated by Django 6.0.6 on 2026-06-20 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novari_base', '0008_deduplicate_existing_image_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.TextField(default='IN_PROGRESS'),
        ),
    ]
